version: "3.0"
services:
  ldap-server:
    image: ldap:latest
    cap_add:
        - SYS_ADMIN
    environment:
      - "DEBIAN_FRONTEND=noninteractive"
    privileged: true
    networks:
      default:
        ipv4_address: 192.168.0.3
  login-server:
    image: head:latest
    volumes:
      - ./docker/head/home:/home
      - ./docker/head/mpishare:/mpishare
      - ./docker/head/opt:/opt
      - ./docker/head/software:/software
    cap_add:
        - SYS_ADMIN
    ports:
      - "2222:22"
    depends_on:
      - ldap-server
    privileged: true
    networks:
      default:
        ipv4_address: 192.168.0.2
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet:  192.168.1.0/16
