version: "3.0"
services:
  ldap-server:
    image: ldap:latest
    cap_add:
        - SYS_ADMIN
    privileged: true
    depends_on:
      - login-server
    networks:
      default:
        ipv4_address: 192.168.0.3
  login-server:
    image: head:latest
    volumes:
      - ./docker/head/nfs:/nfs
    cap_add:
        - SYS_ADMIN
    ports:
      - "2222:22"
    privileged: true
    networks:
      default:
        ipv4_address: 192.168.0.2
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet:  192.168.1.0/16
