version: "3.0"
services:
  ldap-nfs:
    image: ldap:latest
    volumes:
      - ./docker/head/nfs:/nfs
    cap_add:
        - SYS_ADMIN
    privileged: true
    networks:
      default:
        ipv4_address: 192.168.0.2
  login-scheduler:
    image: head:latest
    depends_on:
      - ldap-nfs
    cap_add:
        - SYS_ADMIN
    ports:
      - "2222:22"
    privileged: true
    networks:
      default:
        ipv4_address: 192.168.0.3
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet:  192.168.1.0/16
