version: "3.0"
services:
  ldap-nfs:
    image: ldap:latest
    volumes:
      - nfs:/nfs
    cap_add:
        - SYS_ADMIN
    privileged: true
  login-scheduler:
    image: head:latest
    volumes:
      - nfs:/nfs
    depends_on:
      - ldap-nfs
    cap_add:
        - SYS_ADMIN
    ports:
      - "2222:22"
    privileged: true
volumes:
  nfs:
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet:  192.168.1.0/16
